from tkinter import *
ap=Tk()
ap.geometry("450x300")
def Info():
    print(f"{ent1.get(),ent2.get(),ent3.get(),ent4.get(),ent5.get(),ent6.get(),ent7.get(),ent8.get()}")
    with open("pass.txt","a") as f:
        f.write(f"{ent1.get(),ent2.get(),ent3.get(),ent4.get(),ent5.get(),ent6.get(),ent7.get(),ent8.get()}\n")
label=Label(text="Registration form",bg="yellow",fg="black",relief=SUNKEN,width=20,pady=15,padx=10)
label.grid(row=0,column=3)
lab1=Label(text="Name",bg="orange",fg="black",width=18)
lab1.grid(row=2,column=2,pady=2)
lab1var=StringVar()
ent1=Entry(ap,textvariable=lab1var)
ent1.grid(row=2,column=3)
lab2=Label(text="Age",bg="orange",fg="black",width=18)
lab2.grid(row=3,column=2,pady=2)
lab2var=StringVar()
ent2=Entry(ap,textvariable=lab2var)
ent2.grid(row=3,column=3)
lab3=Label(text="Height",bg="orange",fg="black",width=18)
lab3.grid(row=4,column=2,pady=2)
lab3var=IntVar()
ent3=Entry(ap,textvariable=lab3var)
ent3.grid(row=4,column=3)
lab4=Label(text="Weight",bg="orange",fg="black",width=18)
lab4.grid(row=5,column=2,pady=2)
lab4var=IntVar()
ent4=Entry(ap,textvariable=lab4var)
ent4.grid(row=5,column=3)
lab5=Label(text="Address",bg="orange",fg="black",width=18)
lab5.grid(row=6,column=2,pady=2)
lab5var=StringVar()
ent5=Entry(ap,textvariable=lab5var)
ent5.grid(row=6,column=3)
lab6=Label(text="Gender",bg="orange",fg="black",width=18)
lab6.grid(row=7,column=2,pady=2)
lab6var=IntVar()
ent6=Entry(ap,textvariable=lab6var)
check1=Checkbutton(text="male",variable=lab6var)
check1.grid(row=7,column=3)
lab7=Label()
lab7var=IntVar()
ent7=Entry(ap,textvariable=lab7var)
check2=Checkbutton(text="female",variable=lab7var)
check2.grid(row=7,column=4)
lab8=Label(text="date of admission",bg="orange",fg="black",width=18)
lab8.grid(row=8,column=2,pady=2)
lab8var=IntVar()
ent8=Entry(ap,textvariable=lab8var)
ent8.grid(row=8,column=3)
sub=Button(text="submit",command=Info)
sub.grid(row=9,column=3,pady=7)
ap.mainloop()