from tkinter import *
ap=Tk()
ap.geometry("456x365")
def get():
    #print(ent1.get.txt())
    print(f"{ent2.get(),ent3.get(),ent4.get(),ent5.get(),ent6.get()}")
    with open("pass.txt","a") as f:
        f.write(f"{ent2.get(),ent3.get(),ent4.get(),ent5.get(),ent6.get()}\n")
label=Label(ap,text="Registration form",foreground="black")
#labelvar=StringVar()
label.grid(row=0,column=3,pady=10)
#ent1=Entry(ap,textvariable=labelvar)
#ent1.grid(row=,column=4)
lab1=Label(text="First name",foreground="black")
lab1.grid(row=1,column=1)
lab1var=StringVar()
ent2=Entry(ap,textvariable=lab1var)
ent2.grid(row=1,column=3)
lab2=Label(text="Second name",foreground="black")
lab2.grid(row=2,column=1)
lab2var=StringVar()
ent3=Entry(ap,textvariable=lab2var)
ent3.grid(row=2,column=3)
lab3=Label(text="email",fg="black")
lab3.grid(row=3,column=1)
lab3var=StringVar()
ent3=Entry(ap,textvariable=lab3var)
ent3.grid(row=3,column=3)
lab4=Label(text="Address",fg="black")
lab4.grid(row=4,column=1)
lab4var=StringVar()
ent4=Entry(ap,textvariable=lab4var)
ent4.grid(row=4,column=3)
lab5=Label(text="phone number",fg="black")
lab5.grid(row=6,column=1)
lab5var=IntVar()
ent5=Entry(ap,textvariable=lab5var)
ent5.grid(row=6,column=3)
but=Button(text="Submit",command=get)
but.grid(row=9,column=3,rowspan=1,pady=5)
lab6=Label(text="gender",fg="black")
lab6.grid(row=7,column=1)
lab6var=IntVar()
lab7var=IntVar()
lab8var=IntVar()
ent6=Entry(ap,textvariable=lab6var)
ent7=Entry(ap,textvariable=lab7var)
ent8=Entry(ap,textvariable=lab8var)
lab6=Checkbutton(text="male",variable=lab6var)
check1=Checkbutton(text="female",variable=lab7var)
check2=Checkbutton(text="other",variable=lab8var)
lab6.grid(row=7,column=3)
check1.grid(row=7,column=4)
check2.grid(row=7,column=5)

ap.mainloop()